### PR TITLE
BREAKING CHANGE: Require Node 8+

### PR DESCRIPTION
**Pull request by paulmelnikow**
For this library, which I expect is in maintenance mode, I don't see a benefit in dropping old LTS, so I dropped 5 but kept 4.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Okay, I'm fine with that. It'll simplify other things: #11

**Comment by paulmelnikow** [comment]
Okay, I'm fine with that. It'll simplify other things: #11 

I don't anticipate a lot of releases here. Should we start with a manual release + changelog process?

**Comment by paulmelnikow** [comment]
Okay, I'm fine with that. It'll simplify other things: #11 

I don't anticipate a lot of releases here. Should we start with a manual release + changelog process?

**Comment by paulmelnikow** [comment]
Okay, I'm fine with that. It'll simplify other things: #11 

I don't anticipate a lot of releases here. Should we start with a manual release + changelog process?

**Comment by gr2m** [comment]
I think we still have to setup semantic release for this repo? Do you want to do that, or shall I?

**Comment by paulmelnikow** [comment]
Please go ahead and set it up 😄 

I can hold off on merging this if you'd like.

**Pull request merged**
